READ ME FIRST

---------------------------------------------------------------------------------------------

The files in this repository concern with the GENeralized Economic comPlexitY (GENEPY)
index defined in "Reconciling contrasting views on economic complexity" (2020) by 
Sciarra C., Chiarotti G., Ridolfi L. & Laio F. 

The MATLAB code solves the function to compute the GENEPY index.
The GENEPY index (GENerealized Economic comPlexitY index) constitutes of the first two
eigenvectors of the proximity matrix P. For countries, the proximity matrix P is 
Ncc = Wcp*Wcp', while for products, the matrix is Gpp = Wcp'*Wcp, with Wcp = M_cp./k_c*k_p'.
The matrix M is the incidence matrix of the binary countries-product bipartite network, 
kc the degree of countries and kp'=sum(Mcp/kc). 
The function allows to choose the group for which to perform the computation, either 
countries or products and returns the values of the first two eigenvectors of the 
proximity matrix and the resulting GENEPY index.

The excel file contains the results of the GENEPY index for countries shown in the main
article during the period 1995 - 2017.

For further requests contact: carla.sciarra@polito.it

---------------------------------------------------------------------------------------------

June 2020

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(1)  # 随机种子，保证每次都相同的 matrix
matrix = np.random.randint(2, size=100).reshape(10, 10)  # 邻接矩阵
matrix

array([[1, 1, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 1, 0, 1],
       [0, 0, 1, 1, 1, 0, 1, 1, 0, 1]])

Matlab 计算的结果：
if countries:
ans =

    0.3151
    0.2586
    0.2137
    0.3281
    0.3548
    0.2681
    0.3107
    0.3033
    0.3835
    0.3836

if products:

ans =

    0.3164
    0.2736
    0.3270
    0.3417
    0.3230
    0.2936
    0.3472
    0.3423
    0.2524
    0.3308

%node degree k_c

kc=sum(M,2); 

% Random walk matrix

RW=M./kc; 

% compute k_p'

kp_1=sum(RW,1);

% compute denominator of the fraction

den=kc*kp_1;

% compute transformation matrix Wcp

W=M./den;  

In [3]:
matrix = np.asmatrix(matrix)
kc = matrix.sum(axis=1)
rw = matrix / kc
kp_1 = rw.sum(axis=0)
den = np.dot(kc, kp_1)
w = matrix / den
pd.DataFrame(w)

0         1         2         3         4         5         6  \
0  0.225141  0.100756  0.000000  0.000000  0.081577  0.171184  0.114943   
1  0.000000  0.176322  0.000000  0.275229  0.142760  0.000000  0.000000   
2  0.000000  0.235097  0.000000  0.000000  0.190347  0.000000  0.000000   
3  0.000000  0.000000  0.303797  0.220183  0.114208  0.239658  0.160920   
4  0.196998  0.088161  0.189873  0.137615  0.071380  0.149786  0.000000   
5  0.000000  0.141058  0.000000  0.000000  0.114208  0.239658  0.160920   
6  0.000000  0.117548  0.253165  0.000000  0.095173  0.199715  0.134100   
7  0.315197  0.141058  0.000000  0.000000  0.000000  0.000000  0.160920   
8  0.262664  0.000000  0.000000  0.183486  0.095173  0.000000  0.134100   
9  0.000000  0.000000  0.253165  0.183486  0.095173  0.000000  0.134100   

          7         8    9  
0  0.117302  0.142687  0.0  
1  0.205279  0.000000  0.0  
2  0.000000  0.332937  0.0  
3  0.000000  0.000000  0.0  
4  0.102639  0.124851  0.0  
5  0.000000  0.199762  0.0  
6  0.136852  0.000000  0.0  
7  0.164223  0.199762  0.0  
8  0.136852  0.000000  0.5  
9  0.136852  0.000000  0.5

In [4]:
# countries
p = w * w.T

# 对角线元素设置为 0
i = [range(len(p))]
p[i, i] = 0

evalues, evectors = np.linalg.eig(p)

order_eig = np.lexsort((np.arange(len(evalues)), abs(evalues)))[::-1]  # 从大到小

evectors = evectors[:, order_eig]
evalues = evalues[order_eig]

e = evectors[:, :2]
theta = evalues[:2].reshape(2, 1)

# (((E(:,:).^2))*lambda(:)).^2+2.*((E(:,:).^2))*(lambda(:).^2)
# TODO : 这里的计算数值还有点问题
np.array(np.square(np.dot(np.square(e), theta)) + 2 * np.square(e) * np.square(theta))

array([[0.13419418],
       [0.087502  ],
       [0.05980403],
       [0.14727654],
       [0.16935552],
       [0.09425776],
       [0.13086278],
       [0.12617786],
       [0.30526539],
       [0.3081895 ]])

In [5]:
np.array(theta)
np.array(e)

array([[ 0.79549846],
       [-0.35626074]])

array([[ 0.31514518, -0.10642384],
       [ 0.25859073, -0.01367167],
       [ 0.21372693,  0.05418545],
       [ 0.32808846,  0.13782218],
       [ 0.35476216, -0.01548206],
       [ 0.26807081, -0.01348253],
       [ 0.31070618,  0.11769798],
       [ 0.30332966, -0.14623135],
       [ 0.38351244,  0.67861275],
       [ 0.38359609, -0.68584464]])

In [6]:
from genepy_index import genepy_index

genepy_index(matrix)

(array([[ 0.31514518, -0.10642384],
        [ 0.25859073, -0.01367167],
        [ 0.21372693,  0.05418545],
        [ 0.32808846,  0.13782218],
        [ 0.35476216, -0.01548206],
        [ 0.26807081, -0.01348253],
        [ 0.31070618,  0.11769798],
        [ 0.30332966, -0.14623135],
        [ 0.38351244,  0.67861275],
        [ 0.38359609, -0.68584464]]),
 array([[0.13419418],
        [0.087502  ],
        [0.05980403],
        [0.14727654],
        [0.16935552],
        [0.09425776],
        [0.13086278],
        [0.12617786],
        [0.30526539],
        [0.3081895 ]]))

## RCA 权重矩阵

$$ RCA_{cp} = \frac{\frac{D_{cp}}{\sum_p{D_{cp}}}}{\frac{\sum_c{D_{cp}}}{\sum_{cp}D_{cp}}} $$

- 分子：国家C通过出口产品P获得的收益 / 该国家出口所有产品获得的总收益
- 分母：所有国家出口产品P所获得的总收益 / 所有国家、所有产品 出口的总收益